spring:
  application:
    name: zuul-gate

server:
  port: 2080

zuul:
  routes:
    baidu:
      path: /baidu/**
#      url: http://localhost:2080/self/ask
      url: forward:/self/ask/
#    error:
#      path: /error/**
#      url: forward:/self/error/
    common:
      path: /common/**
      url: forward:/self/common/
  retryable: false

management:
  endpoints:
    web:
      exposure:
        include: "*"