spring:
  application:
    name: cloud-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          # 请求服务名称可以用小写
          lower-case-service-id: true
      routes:
#        - id: cloud-user
#          uri: lb://cloud-user
#          predicates:
#            - Path=/user/**
#        - id: cloud-order
#          uri: lb://cloud-order
#          predicates:
#            - Query=foo, ba
#        - id: redirect-baidu
#          uri: http://www.baidu.com
#          predicates:
#            - Method=GET
        # 自定义路由断言工厂 那个args的地方是真的坑， 位置不对不对齐就不行 但是为什么不生效
        - id: customer-route
          uri: lb://cloud-user
          predicates:
            - Path=/user/order/**
            - AgeAuth=18,60
#            - name: CheckAuth
#              args:
#                name: killer1
        - id: order-route
          uri: lb://cloud-order
          order: 1
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1 # 转发前去掉一层路径
            - Log=true,true

server:
  port: 9999
