spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  #    loadbalancer:
  #      ribbon:
  #        #use ReactorLoadBalancerExchangeFilterFunction
  #        enabled: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379


logging:
  level:
    org.wrh.cloud.gateway: debug