spring:
  application:
    name: cloud-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          # 请求服务名称可以用小写
          lower-case-service-id: true

      #测试环境暂不需要设置
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: #设置支持的域名
              - "http://service1.bb.co"
              - "http://service2.bb.co"
            allowedHeaders: "*" # 支持的方法
            allowCredentials: true # 设置允许携带cookie，为true时allowedOrigins不允许为*会报错
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
      routes:
#        - id: cloud-user
#          uri: lb://cloud-user
#          predicates:
#            - Path=/user/**
#        - id: cloud-order
#          uri: lb://cloud-order
#          predicates:
#            - Query=foo, ba
#        - id: redirect-baidu
#          uri: http://www.baidu.com
#          predicates:
#            - Method=GET
        # 自定义路由断言工厂 那个args的地方是真的坑， 位置不对不对齐就不行 但是为什么不生效
        - id: customer-route
          uri: lb://cloud-user
          predicates:
            - Path=/user/**
            - AgeAuth=18,60
#            - name: CheckAuth
#              args:
#                name: killer1
        - id: order-route
          uri: lb://cloud-order
          order: 1
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1 # 转发前去掉一层路径
            - Log=true,true
#       熔断测试
        - id: user-service
          uri: lb://cloud-user
          predicates:
            - Path=/hystrix/**
          filters:
#            - StripPrefix=1 # 转发前去掉一层路径
            name: Hystrix
            args:
              name: fallbackcmd
              fallbackUrl: forward:/fallback

server:
  port: 9999
