#spring:
#  application:
#    name: cloud-user
#  profiles:
#    active: dev

server:
  port: 20005

user:
  hobby: car

hobby: car

spring:
  sleuth:
    sampler:
      rate: 100 # 指定采样比例，默认10%
    messaging:
      enabled: true