spring:
  cloud:
    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
      config:

        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
        file-extension: yml
  #    loadbalancer:
  #      ribbon:
  #        #use ReactorLoadBalancerExchangeFilterFunction
  #        enabled: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 10


logging:
  level:
    org.wrh.cloud.user: debug